name: flutter_news_app_web_dashboard_full_source_code
description: "A Flutter web application for comprehensive content management and administration within the Flutter News App Full Source Code Toolkit."
repository: https://github.com/flutter-news-app-full-source-code/flutter-news-app-web-dashboard-full-source-code
publish_to: none
version: 1.6.0

environment:
  sdk: ^3.9.0

dependencies:
  auth_api:
    git:
      url: https://github.com/flutter-news-app-full-source-code/auth-api.git
      ref: v1.0.1
  auth_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/auth-client.git
      ref: v1.0.1
  auth_inmemory:
    git:
      url: https://github.com/flutter-news-app-full-source-code/auth-inmemory
      ref: v1.1.0
  auth_repository:
    git:
      url: https://github.com/flutter-news-app-full-source-code/auth-repository.git
      ref: v1.0.1
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  collection: ^1.19.1
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: v1.3.1
  data_api:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-api.git
      ref: v1.0.1
  data_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-client.git
      ref: v1.0.1
  data_inmemory:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-inmemory.git
      ref: v1.1.0
  data_repository:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-repository.git
      ref: v1.0.1
  data_table_2: ^2.6.0
  device_preview: ^1.2.0
  equatable: ^2.0.7
  fl_chart: ^1.0.0
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.3+1
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  http_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/http-client.git
      ref: v1.0.1
  intl: ^0.20.2
  kv_storage_service:
    git:
      url: https://github.com/flutter-news-app-full-source-code/kv-storage-service.git
      ref: v1.0.1
  kv_storage_shared_preferences:
    git:
      url: https://github.com/flutter-news-app-full-source-code/kv-storage-shared-preferences.git
      ref: v1.0.1
  logging: ^1.3.0
  pinput: ^6.0.0
  rxdart: ^0.28.0
  stream_transform: ^2.1.1
  timeago: ^3.7.1
  ui_kit:
    git:
      url: https://github.com/flutter-news-app-full-source-code/ui-kit.git
      ref: v1.0.1
  uuid: ^4.5.1

dev_dependencies:
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true

dependency_overrides:
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: ff027602d9b33447b3595855f7a548e308d41945
  http_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/http-client.git
      ref: v1.1.0