name: flutter_news_app_web_dashboard_full_source_code
description: "A Flutter web application for comprehensive content management and administration within the Flutter News App Full Source Code Toolkit."
repository: https://github.com/flutter-news-app-full-source-code/flutter-news-app-web-dashboard-full-source-code
publish_to: none
version: 1.12.0

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  collection: ^1.19.1
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: 28c7a57b5ce05e23ff70b953e067e3643368aea6
  core_ui:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core-ui.git
      ref: 6c36e18320e60ce202e64c564f3848da73cd2306
  data_table_2: ^2.6.0
  dotted_border: ^3.1.0
  equatable: ^2.0.7
  file_picker: ^10.3.10
  fl_chart: ^1.0.0
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.3+1
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  http_parser: ^4.1.2
  intl: ^0.20.2
  logging: ^1.3.0
  pinput: ^6.0.0
  rxdart: ^0.28.0
  stream_transform: ^2.1.1
  timeago: ^3.7.1
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mockingjay: ^2.1.0
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
